package varnishapi

var _tags = map[string]string{
	"ReqStart":       "client.ip",
	"ReqMethod":      "req.method",
	"ReqURL":         "req.url",
	"ReqProtocol":    "req.proto",
	"ReqHeader":      "req.http.",
	"ReqUnset":       "unset req.http.",
	"RespProtocol":   "resp.proto",
	"RespStatus":     "resp.status",
	"RespReason":     "resp.reason",
	"RespHeader":     "resp.http.",
	"RespUnset":      "unset resp.http.",
	"BereqMethod":    "bereq.method",
	"BereqURL":       "bereq.url",
	"BereqProtocol":  "bereq.proto",
	"BereqHeader":    "bereq.http.",
	"BereqUnset":     "unset bereq.http.",
	"BerespProtocol": "beresp.proto",
	"BerespStatus":   "beresp.status",
	"BerespReason":   "beresp.reason",
	"BerespHeader":   "beresp.http.",
	"BerespUnset":    "unset beresp.http.",
	"ObjProtocol":    "obj.proto",
	"ObjStatus":      "obj.status",
	"ObjReason":      "obj.reason",
	"ObjHeader":      "obj.http.",
	"ObjUnset":       "unset obj.http.",
}
